# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
 - name: from_email_address
   value: MS_ksDev1@test-dnvo4d998erg5r86.mlsender.net

 - name: to_email_address
   value: ron_lim_az500_ms@outlook.com

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - main.py
    exclude:
    - README.md
    - test-github-pipelines.yml

pool:
  name: rhelpool

steps:
- task: CmdLine@2
  displayName: "Sync Changes to linux"
  inputs:
    script: 'git pull'
    workingDirectory: '/root/gitrepos/pythonlinux/pythonlinux'

- task: CmdLine@2
  displayName: "Run Python Script"
  inputs:
    script: 'sudo python /root/gitrepos/pythonlinux/pythonlinux/main.py > /root/pythonlogs/main.py.log &'

- task: CmdLine@2
  displayName: "Send Python with attached output log and image Email"
  inputs:
    script: 'echo -e "Python output in the attachment\nThanks,\nRonald Stewart Lim" | mail -s "Python output notification `date +"%Y-%m-%d"`" -a /root/pythonimages/plot_image.png -a /root/pythonlogs/main.py.log -r $(from_email_address) $(to_email_address)'

- task: CmdLine@2
  displayName: "Rename logs with date and time"
  inputs:
    script: 'mv /root/pythonlogs/main.py.log /root/pythonlogs/main.py.`date +"%Y-%m-%d-%I-%M-%p"`.log'

- task: CmdLine@2
  displayName: "Rename image with date and time"
  inputs:
    script: 'mv /root/pythonimages/plot_image.png /root/pythonlogs/plot_image_`date +"%Y-%m-%d-%I-%M-%p"`.png'