# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: rhelpool

steps:
- task: CmdLine@2
  inputs:
    script: 'git pull'
    workingDirectory: '/root/gitrepos/pythonlinux/pythonlinux'

- task: CmdLine@2
  inputs:
    script: 'sudo python /root/gitrepos/pythonlinux/pythonlinux/main.py > /root/pythonlogs/main.py.`date +"%Y-%m-%d"`.log &'

